# Use container-based infrastructure
sudo: true

language: scala

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

# This is an sbt plugin, so this section is for demo purpose
scala:
   - 2.11.8

jdk:
  - oraclejdk8

env:
  # This splits the build into two parts
  matrix:
    - TEST_COMMAND="scripted sbt-assembly/*"
    - TEST_COMMAND="scripted merging/* caching/*"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libssl1.0.0
  - curl -O https://packages.couchbase.com/releases/4.5.0/couchbase-server-community_4.5.0-ubuntu12.04_amd64.deb && sudo dpkg -i couchbase-server-community_4.5.0-ubuntu12.04_amd64.deb

before_script:
  - cat /etc/*release*
  - uname -a

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm